import type { Commander } from 'cli'
import type {
  DiscoveredGraphqlClient,
  GraphqlClientLike,
} from 'commands/space/shared/discover-graphql-clients.ts'

import { assertProjectType } from 'commands/generate/shared/project.ts'
import {
  clientBaseName,
  discoverGraphqlClients,
  isCheckedExternalSchemaApplication,
} from 'commands/space/shared/discover-graphql-clients.ts'
import { introspectionToSdl } from 'commands/generate/graphql-schema/introspection.ts'
import { dirname, relative } from '@std/path'
import logger from '@zanix/utils/logger'

/**
 * One `**\/*.client.ts` export this generator actually acts on — a `GraphQLClient`-shaped export
 * whose `schemaApplication` is the object form `{ external: true }`
 * (`isCheckedExternalSchemaApplication`, `discover-graphql-clients.ts`), paired with the exact
 * `gql/<name>.schema.graphql` path Layer 2's own cache-match path
 * (`checkGraphqlSchemas`/`commands/space/shared/graphql-check.ts`) reads back later. A client with
 * a plain Application name, the plain `'external'` string (syntax-only, no cache needed), or no
 * `schemaApplication` at all is never a target — this generator has nothing to do for any of them.
 */
export interface GraphqlSchemaTarget {
  file: string
  exportName: string
  cachePath: string
  instance: GraphqlClientLike
}

/**
 * Pure planning: narrows `discoverGraphqlClients`'s own already-resolved result down to
 * {@linkcode GraphqlSchemaTarget}s — see that interface's own doc for exactly which clients qualify.
 * `<name>` is derived identically to Layer 2's own match (`clientBaseName`,
 * `discover-graphql-clients.ts`) — the basename of a `**\/*.client.ts` file, minus that suffix — so
 * this generator's output and Layer 2's own lookup can never name the same client's cache two
 * different ways.
 *
 * @param clients - {@linkcode discoverGraphqlClients}'s own result for the target project.
 * @param gqlDir - The project's `gql/` directory, already resolved to an absolute path.
 */
export function planGraphqlSchemaTargets(
  clients: DiscoveredGraphqlClient[],
  gqlDir: string,
): GraphqlSchemaTarget[] {
  return clients
    .filter((client) => isCheckedExternalSchemaApplication(client.schemaApplication))
    .map((client) => ({
      file: client.file,
      exportName: client.exportName,
      cachePath: `${gqlDir}/${clientBaseName(client.file)}.schema.graphql`,
      instance: client.instance,
    }))
}

/** One {@linkcode GraphqlSchemaTarget} this generator failed to introspect/cache for — its own
 * `.introspect()` call threw (a disabled-introspection response, a real network failure, ...), or
 * the raw result it resolved with failed `graphql-js`'s own `buildClientSchema()`. Reported per
 * client; every OTHER target still gets a real, independent attempt — see
 * {@linkcode writeGraphqlSchemaCaches}'s own doc for why. */
export interface GraphqlSchemaCacheFailure {
  file: string
  exportName: string
  error: Error
}

/**
 * The `#`-comment header prepended to every written `gql/<name>.schema.graphql` — `#` is a real
 * GraphQL SDL comment (ignored by `parse()`/`buildSchema()`, so it's fully transparent to Layer 2's
 * own `validate()` call on this same file), not a hack. Warns against hand-editing: this file is a
 * snapshot of what a REAL remote API actually answered with — a manual edit doesn't change what
 * that API accepts, it just makes this cache lie about it (Layer 2 would then validate queries
 * against a schema that no longer matches reality), and any edit gets silently overwritten the next
 * time this command runs anyway.
 */
function buildCacheHeader(target: GraphqlSchemaTarget, projectRoot: string): string {
  // Relative to the project root, never the absolute path `discoverGraphqlClients` resolves
  // internally — an absolute path would make this committed file differ by machine/checkout
  // location for the exact same real schema, a spurious diff nobody wants from a lockfile-like
  // artifact.
  const relativeFile = relative(projectRoot, target.file)
  return (
    '# AUTO-GENERATED by `zanix generate graphql-schema` — do not hand-edit.\n' +
    `# Source: ${target.exportName} (${relativeFile}), introspected live from that client's own\n` +
    "# baseUrl. Reflects the remote API's real schema at generation time — editing this file by\n" +
    "# hand won't change what that API actually accepts, and your edit will be silently\n" +
    '# overwritten next time this command runs.\n' +
    '# To refresh: zanix generate graphql-schema\n\n'
  )
}

/**
 * Real orchestration: a real, live `.introspect()` network call per `target.instance` (a
 * `GraphQLClient` subclass instance {@linkcode discoverGraphqlClients} already imported and
 * duck-typed for real — never re-instantiated here), converted to SDL via
 * {@linkcode introspectionToSdl}, then written to `target.cachePath`.
 *
 * Every target is attempted independently (`Promise.all`, never a sequential loop that stops at
 * the first failure) — a single flaky or introspection-disabled external API reports exactly one
 * failure instead of silently hiding every other client's own successful result behind it. A
 * target's `cachePath` is only ever written once BOTH `.introspect()` and `introspectionToSdl()`
 * succeed for it — a failed target's existing cache file (from a previous successful run, if any)
 * is left completely untouched, never truncated or overwritten with partial content.
 *
 * @param targets - {@linkcode planGraphqlSchemaTargets}'s own result for this run.
 * @param projectRoot - The project root, used only to render a relative, machine-independent
 * source path in each cache file's own header comment (see {@linkcode buildCacheHeader}).
 * @returns Every `cachePath` actually written, plus every target that failed (with a real `Error`,
 * never a raw/opaque one) — facts only, the same "report, decide separately" split
 * `runGraphqlCheck` (`graphql-check.ts`) already uses.
 */
export async function writeGraphqlSchemaCaches(
  targets: GraphqlSchemaTarget[],
  projectRoot: string,
): Promise<{ written: string[]; failures: GraphqlSchemaCacheFailure[] }> {
  const written: string[] = []
  const failures: GraphqlSchemaCacheFailure[] = []

  await Promise.all(targets.map(async (target) => {
    try {
      const introspect = target.instance.introspect
      if (typeof introspect !== 'function') {
        throw new Error(
          "This export's own .introspect() is not a function — is it a real GraphQLClient " +
            'subclass instance?',
        )
      }
      const raw = await (introspect as () => Promise<Record<string, unknown>>).call(
        target.instance,
      )
      const sdl = await introspectionToSdl(raw)
      await Deno.mkdir(dirname(target.cachePath), { recursive: true })
      await Deno.writeTextFile(target.cachePath, buildCacheHeader(target, projectRoot) + sdl)
      written.push(target.cachePath)
    } catch (error) {
      failures.push({
        file: target.file,
        exportName: target.exportName,
        error: error instanceof Error ? error : new Error(String(error)),
      })
    }
  }))

  return { written, failures }
}

/**
 * `zanix generate graphql-schema [root]`'s real orchestration: discovers every `**\/*.client.ts`
 * export under the project (`discoverGraphqlClients`, shared with Layer 2 — see that module's own
 * doc), narrows to the ones opted into Case B's cache/validate path
 * (`planGraphqlSchemaTargets`), and, for each, runs a REAL network introspection call and writes
 * real SDL text to `gql/<name>.schema.graphql` — see {@linkcode writeGraphqlSchemaCaches}'s own
 * doc for exactly how.
 *
 * Deliberately regenerates every target's cache file on every run, unlike every other generator on
 * this page except `openapi` — the same reasoning: a `gql/<name>.schema.graphql` file is a
 * machine-derived snapshot of a live, external API's own current schema, not a hand-editable shell
 * a generator seeds once and leaves alone. Re-running is how a stale cache (the external API added
 * a field, deprecated another, ...) gets refreshed.
 *
 * This is the one generator, alongside `openapi`, that reaches OUTSIDE the target project's own
 * source at all — here, a REAL network call to each target client's own `baseUrl`, never a `deno
 * run` subprocess (there is no local code to statically introspect; a real HTTP round-trip is the
 * only way to learn an external schema's real current shape). No `--verify` flag, same reasoning
 * `openapi` documents for its own absence: the output is plain SDL text with zero imports, nothing
 * for `deno check` to check.
 *
 * A project with zero clients opted into `{ external: true }` is a clean no-op (an info log, no
 * error) — most projects never need this generator at all; Layer 2's own `'external'` (plain
 * string) already covers the common "syntax-only, no cache" case with zero setup.
 *
 * @throws {Error} (via `this.throw`) When at least one target failed introspection — AFTER every
 * other target has already been attempted and, if successful, written; never on the first failure.
 */
async function generateGraphqlSchemaAction(
  this: Commander,
  _options: unknown,
  root?: string,
) {
  assertProjectType(this, ['space', 'space-server'], 'graphql-schema', root)

  const projectRoot = root ?? Deno.cwd()
  const gqlDir = `${projectRoot}/src/space/gql`

  const clients = await discoverGraphqlClients(projectRoot)
  const targets = planGraphqlSchemaTargets(clients, gqlDir)

  if (targets.length === 0) {
    logger.info(
      'No GraphQL client with schemaApplication: { external: true } found under this project — ' +
        'nothing to introspect.',
    )
    return
  }

  const { written, failures } = await writeGraphqlSchemaCaches(targets, projectRoot)

  for (const cachePath of written) {
    logger.info(`GraphQL schema cached successfully to '${cachePath}'.`)
  }

  if (failures.length > 0) {
    const lines = failures.map((failure) =>
      `${failure.file} (${failure.exportName}): ${failure.error.message}`
    )
    this.throw(
      new Error(
        `${failures.length} client(s) failed introspection — no cache file was written for any ` +
          `of them (an existing cache, if any, was left untouched):\n${
            lines.map((line) => `  - ${line}`).join('\n')
          }`,
      ),
    )
  }
}

export default generateGraphqlSchemaAction

export function registerGraphqlSchemaCommand(cwd: Commander): void {
  cwd.command('graphql-schema')
    .description(
      'Introspect every GraphQL client opted into schemaApplication: { external: true } and ' +
        "cache its real, live schema as SDL text to 'gql/<name>.schema.graphql' — read back by " +
        "'zanix space build'/'zanix space dev's GraphQL check step (Layer 2) to validate that " +
        "client's queries for real, the same way it already does for a locally compiled schema. " +
        'OVERWRITES each target cache file on every run — a machine-derived snapshot of a live, ' +
        'external API, not a hand-editable shell.',
    )
    .arguments('[root:string]')
    .action((options, ...args) => {
      return generateGraphqlSchemaAction.call(cwd, options, ...args)
    })
}
