import { resolveSpaceUiVersion } from 'commands/new/lib/tree/projects/space-icons.ts'
import { readFileFromCurrentUrl } from 'utils/read-current-file.ts'
import { join } from '@std/path'

/**
 * `--theme default`'s own scaffold side effect — copies `@zanix/space-ui`'s curated starter
 * theme (`src/templates/theme/tokens.css` + `src/templates/shared/{behavior,card}.css`) into a
 * generated project's own top-level `theme/` folder, as a plain set of files the project owns
 * outright — same JSR-fetch mechanism `space-icons.ts`'s `--icons` already uses
 * (`resolveSpaceUiVersion`, reused unchanged from there rather than duplicated here), and the same
 * "never a runtime dependency" contract: nothing generated by this module ever adds
 * `@zanix/space-ui` to the project's own `deno.json` — these are plain `.css` files, wired into
 * `space.app.ts`'s `globalCss` (`@zanix/space`'s own `docs/theming.md` convention, unchanged),
 * never a `.ts` import.
 *
 * Lives at the project ROOT (`./theme/`), a sibling of `assets/`/`src/` — deliberately NOT nested
 * under `assets/theme/`: `assetsDir` (always declared, see `getSpaceAppTemplate`'s own doc in
 * `space.ts`) recursively scans and publicly serves every file under it as a raw static asset, so a
 * theme stylesheet placed there would be duplicated — once via its own bundled `globalCss` include,
 * once via `assetsDir`'s raw scan of the same file sitting inside its scanned tree — producing two
 * `<link>`s per stylesheet and a layout regression on mobile from the un-bundled duplicate's own
 * cascade position. `theme/` living outside `assetsDir`'s scan path is what keeps these two
 * mechanisms from ever double-serving the same bytes.
 *
 * Also writes a fourth file, `space-defaults.css` — real styling for `@zanix/space`'s own built-in
 * `[data-space="not-found"]`/`[data-space="error"]` views and the CLI's own scaffolded templates
 * (`--template welcome`/`population`, both sharing one `[data-space="content"]` root element — see
 * `space-welcome.ts`'s own doc for why) — EMBEDDED here ({@linkcode LOCAL_SPACE_DEFAULTS_CSS}),
 * not JSR-fetched like the other three: `@zanix/space-ui`'s own repo already carries the canonical
 * source at `src/templates/theme/space-defaults.css` (kept byte-identical to the embedded constant
 * below — `space-theme.test.ts`'s own integrity test proves it), but the currently pinned,
 * PUBLISHED version this module fetches from (`ZANIX_DEPENDENCY_VERSIONS['@zanix/space-ui']`,
 * `0.1.0` as of writing) predates that file — it simply isn't there to fetch yet. See
 * {@linkcode LOCAL_SPACE_DEFAULTS_CSS}'s own doc for the real, tracked follow-up this implies.
 *
 * Genuinely independent of `--icons` (which writes `assets/icons/` + a real `@zanix/space-ui` TS
 * import; `assetsDir` itself is unconditional now, see above) — the two features happen to share a
 * source package and a JSR-fetch mechanism, nothing more. Also independent of `--template`: neither
 * this theme nor `'astronaut'` (`space-astronaut.ts`) changes `routes/`/`comets/` CONTENT — that's
 * `--template`'s own axis (see `space.ts`'s own doc) — only whether `space.app.ts` declares a
 * `globalCss` list and whether these four files land on disk.
 *
 * @module
 */

/**
 * One JSR-fetched theme file this side effect copies — `source` is the path `@zanix/space-ui`
 * itself uses, relative to its own `src/templates/`; `target` is the flat, single-folder path this
 * scaffold writes it to instead, relative to `${root}/theme/`. Deliberately NOT a 1:1 mirror of
 * `space-ui`'s own `theme/`+`shared/` split (unlike `--icons`, which mirrors `shared/icons/`
 * verbatim): that split exists to organize `space-ui`'s OWN repo (a "what varies by visual
 * identity" vs. "what's theme-agnostic" distinction that matters to that package's maintainers),
 * not something a consuming project's own `theme/` layout needs to reproduce — flattening avoids a
 * confusing `theme/theme/tokens.css` double segment.
 */
export interface ThemeTemplateFile {
  source: string
  target: string
}

/**
 * Exported (not private) so a test can assert this matches exactly what `@zanix/space-ui` itself
 * ships (at its currently pinned, PUBLISHED version) across `src/templates/theme/tokens.css` +
 * `src/templates/shared/{behavior,card}.css` (minus the icon catalog, which `--icons`/
 * `space-icons.ts` already owns independently, and minus `space-defaults.css`, which isn't
 * published yet — see {@linkcode LOCAL_SPACE_DEFAULTS_CSS}'s own doc) — without re-implementing
 * that package's own template-content tests. This side just needs to know WHICH files to
 * fetch/copy and where to put them, never validate their contents.
 *
 * Declaration order matches {@linkcode getThemedGlobalCssPaths}'s own real `globalCss` order —
 * `tokens.css` first (declares the custom properties every other file only ever consumes via
 * `var(...)`), then `behavior.css`/`card.css` (theme-agnostic, `space-ui`'s own structural/layout
 * starters).
 */
export const THEME_TEMPLATE_FILES: ThemeTemplateFile[] = [
  { source: 'theme/tokens.css', target: 'tokens.css' },
  { source: 'shared/behavior.css', target: 'behavior.css' },
  { source: 'shared/card.css', target: 'card.css' },
]

/**
 * `space-defaults.css`'s own real content, embedded here VERBATIM rather than JSR-fetched — see
 * this module's own doc for why. Byte-identical to `@zanix/space-ui`'s own local checkout at
 * `src/templates/theme/space-defaults.css` (`space-theme.test.ts`'s own integrity test asserts
 * this directly), which stays the canonical source to edit; this constant is a deliberate,
 * documented copy, not a second independent authoring surface.
 *
 * **Real, tracked follow-up**: once a future `@zanix/space-ui` release republishes with
 * `theme/space-defaults.css` actually included, this constant should be deleted and
 * `{ source: 'theme/space-defaults.css', target: 'space-defaults.css' }` added to
 * {@linkcode THEME_TEMPLATE_FILES} instead — the same real JSR fetch every other entry there
 * already gets, closing this gap for good.
 *
 * Targets `@zanix/space`'s own `[data-space="not-found"|"error"|"content"]` hooks — real, minimal
 * styling (centered content, a comfortable measure, the app's own primary color for outbound
 * links, plus generic `h2`/`code`/`pre` treatment), referencing only semantic `--space-*` tokens
 * from `tokens.css` (never a primitive, never a literal), same discipline `behavior.css` already
 * follows. `"content"` is the ONE shared root-element value every CLI-scaffolded template uses
 * (`welcome`, `population`, and any future one — see `space-welcome.ts`'s own doc for why), never a
 * per-`--template` value.
 *
 * The embedded content's own header comment still says `--template themed` (not `--theme
 * default`), even after this scaffold's own theme/template decoupling — deliberately: it's a
 * byte-identical copy of `@zanix/space-ui`'s own upstream file (see above), which this package
 * doesn't own and isn't this file's to edit independently. Update it here only once that upstream
 * file itself is updated to match.
 */
export const LOCAL_SPACE_DEFAULTS_CSS = `/*
 * Space-UI default theme — @zanix/space built-in view styling
 * -------------------------------------------------------------
 * Scaffolded by \`zanix new space --template themed\`, alongside \`./tokens.css\` and
 * \`../shared/{behavior,card}.css\` — a plain file the new project owns outright: no import, no
 * version pin, edit/extend/delete freely. Not imported by any \`@zanix/space-ui\` runtime code, and
 * not imported by \`@zanix/space\` either — nothing in either package breaks if this file never
 * existed.
 *
 * Deliberately separate from \`../shared/behavior.css\`: that file is scoped to \`@zanix/space-ui\`'s
 * OWN \`[data-space-ui="..."]\` component hooks (a different package, a different audience — see
 * that file's own header). This one targets \`@zanix/space\`'s own \`[data-space="..."]\` hooks
 * instead — the stable attribute the framework's built-in \`not-found\`/\`error\` fallback views (and
 * the CLI's own scaffolded templates — \`welcome\`, \`population\`) render on their root element.
 * \`data-space\` and \`data-space-ui\` are two independent attributes on purpose: \`@zanix/space\` and
 * \`@zanix/space-ui\` are two independent packages, and neither one's markup contract belongs to the
 * other.
 *
 * Every CLI-scaffolded template shares ONE generic root-element value, \`data-space="content"\` —
 * never a per-\`--template\` value (\`welcome\`, \`population\`, and any future one all render the exact
 * same \`<main data-space="content">\`, see \`@zanix/cli\`'s own \`space-welcome.ts\` doc for why): a
 * future scaffolded template joins this same selector list automatically, with zero CSS changes
 * needed here, rather than needing a parallel, duplicated rule set added per template.
 *
 * Every rule below references only SEMANTIC \`--space-*\` tokens declared in \`./tokens.css\` (never a
 * primitive, never a literal) — the same discipline \`../shared/behavior.css\` already follows, so a
 * host overriding this project's palette (\`docs/theming.md\`'s own base→host cascade) restyles
 * these views too, with no separate mechanism.
 *
 * Deliberately minimal — a coherent, readable starting point, not a full redesign: centered content,
 * a comfortable measure, and the app's own primary color for the one interactive element
 * (a scaffolded page's own outbound links). Delete or replace freely.
 *
 * \`code\`/\`pre\` below are the one deliberate exception to the \`[data-space="..."]\`-scoped pattern
 * above — genuinely content-agnostic (any inline code snippet or literal source excerpt, on any
 * page, any \`--template\`), matching \`../shared/behavior.css\`'s own unscoped \`[data-space-ui="..."]\`
 * component hooks. \`--template population\`'s own tutorial content (an ICU catalog excerpt, several
 * \`<code>\` filenames) is the first real content this scaffold generates that uses either.
 */

[data-space='not-found'],
[data-space='error'] {
  display: block;
  margin: 3rem auto;
  max-width: 32rem;
  padding: 0 var(--space-space-md, 1rem);
  text-align: center;
  color: var(--space-color-ink);
}

[data-space='content'] {
  margin: 3rem auto;
  max-width: 32rem;
  padding: 0 var(--space-space-md, 1rem);
  color: var(--space-color-ink);
}

[data-space='content'] a {
  color: var(--space-color-primary);
}

[data-space='content'] a:hover {
  color: var(--space-color-primary-strong);
}

[data-space='content'] h2 {
  margin-top: 2.5rem;
  margin-bottom: 0.75rem;
  color: var(--space-color-ink);
}

code {
  padding: 0.15rem 0.4rem;
  border: 1px solid var(--space-color-border);
  border-radius: 4px;
  background: var(--space-color-surface);
  color: var(--space-color-ink);
  font-family: ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace;
  font-size: 0.86em;
}

pre {
  padding: 0.75rem 1rem;
  overflow-x: auto;
  border: 1px solid var(--space-color-border);
  border-radius: 6px;
  background: var(--space-color-surface);
  color: var(--space-color-ink);
  font-family: ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace;
  font-size: 0.86em;
  line-height: 1.5;
}
`

/** Where {@linkcode LOCAL_SPACE_DEFAULTS_CSS} lands, relative to `${root}/theme/` — same flat
 * convention every {@linkcode THEME_TEMPLATE_FILES} entry's own `target` already follows. */
export const LOCAL_SPACE_DEFAULTS_CSS_TARGET = 'space-defaults.css'

/**
 * The real `globalCss` entries {@linkcode getSpaceAppTemplate} (`space.ts`) writes for `--theme
 * default` — `./theme/<target>`, one per {@linkcode THEME_TEMPLATE_FILES} entry (same declaration
 * order), plus {@linkcode LOCAL_SPACE_DEFAULTS_CSS_TARGET} LAST — it's the one file that targets
 * `@zanix/space`'s own built-in views, layered on top of everything above it, so it must be free
 * to override anything `tokens.css`/`behavior.css`/`card.css` themselves declare for the same
 * selector (today, none do — but cascade order should still reflect intent, not coincidence).
 * Exported standalone so both `space.ts` and a test can share the exact same list, rather than a
 * test re-deriving it by hand and risking drift.
 */
export function getThemedGlobalCssPaths(): string[] {
  return [
    ...THEME_TEMPLATE_FILES.map(({ target }) => `./theme/${target}`),
    `./theme/${LOCAL_SPACE_DEFAULTS_CSS_TARGET}`,
  ]
}

/**
 * Fetches one theme file's raw content from `@zanix/space-ui`'s own `src/templates/` at the
 * resolved version — same `readFileFromCurrentUrl` machinery, and the same already-resolved-version
 * discipline, as `getSpaceUiIconTemplate` (`space-icons.ts`): this NEVER goes through a live
 * "latest" lookup path, not even indirectly. See that function's own doc for why the `{current}`
 * placeholder segment is required, not optional.
 *
 * @param source - A {@linkcode ThemeTemplateFile}'s own `source` (e.g. `'theme/tokens.css'`).
 */
export async function getSpaceUiThemeTemplate(source: string): Promise<string> {
  const version = resolveSpaceUiVersion()
  const url = `https://jsr.io/@zanix/space-ui/${version}/src/templates/{current}`
  return await readFileFromCurrentUrl(url, source)
}

/**
 * Writes already-resolved theme file contents to `${root}/theme/<target>` — flat, per
 * {@linkcode THEME_TEMPLATE_FILES}'s own `target` — plus {@linkcode LOCAL_SPACE_DEFAULTS_CSS}
 * (unconditionally, no fetch needed for it). Takes already-fetched content for the JSR-fetched
 * trio rather than fetching itself, so this half of the side effect (the part that needs no JSR
 * access) is testable independently of the publish gate in `resolveSpaceUiVersion` — same split
 * `writeIconCatalogFiles` already establishes for `--icons`.
 *
 * @param contents - Keyed by `source` (a {@linkcode THEME_TEMPLATE_FILES} entry's own `source`),
 * not `target` — the same key {@linkcode copyThemeAssets} naturally has on hand right after
 * fetching, before this function maps each entry to its own `target` path.
 */
export async function writeThemeFiles(
  root: string,
  contents: Record<string, string>,
): Promise<void> {
  const targetDir = join(root, 'theme')
  await Deno.mkdir(targetDir, { recursive: true })

  await Promise.all([
    ...THEME_TEMPLATE_FILES.map(({ source, target }) => {
      const content = contents[source]
      if (content === undefined) {
        throw new Error(`writeThemeFiles: missing content for "${source}"`)
      }
      return Deno.writeTextFile(join(targetDir, target), content)
    }),
    Deno.writeTextFile(
      join(targetDir, LOCAL_SPACE_DEFAULTS_CSS_TARGET),
      LOCAL_SPACE_DEFAULTS_CSS,
    ),
  ])
}

/**
 * Best-effort removal of exactly the one path {@linkcode copyThemeAssets} itself ever writes —
 * `${root}/theme/` — nothing else. Called only from `copyThemeAssets`'s own catch, right
 * before it rethrows, same reasoning as `space-icons.ts`'s own `cleanupIconCatalogOutput`:
 * `writeThemeFiles`'s concurrent `Deno.writeTextFile` calls (`Promise.all`) can leave a subset of
 * the four files written if one rejects while the others already succeeded, and this guarantees
 * the theme folder is always either fully present or fully absent after a failed
 * `copyThemeAssets`. A `Deno.errors.NotFound` (the common case — the gate throws before anything
 * was ever written) is expected and silently ignored, same as any other cleanup outcome.
 */
async function cleanupThemeOutput(root: string): Promise<void> {
  try {
    await Deno.remove(join(root, 'theme'), { recursive: true })
  } catch (error) {
    if (!(error instanceof Deno.errors.NotFound)) throw error
  }
}

/**
 * The full `--theme default` side effect: fetches every {@linkcode THEME_TEMPLATE_FILES} entry
 * from the resolved `@zanix/space-ui` version, writes them (plus the embedded
 * {@linkcode LOCAL_SPACE_DEFAULTS_CSS}) via {@linkcode writeThemeFiles}. Runs strictly independent
 * of `--icons`/`--renderer` — nothing here reads either, by design (see this module's own doc).
 *
 * Still throws on any failure — same contract as `copyIconCatalog` (`space-icons.ts`): its caller,
 * `ensureSpaceScaffoldSideEffects`, is what decides to catch and degrade gracefully instead of
 * propagating further. On failure, first runs {@linkcode cleanupThemeOutput} to remove any of its
 * OWN partial output, then rethrows the original error completely unchanged (never wrapped, never
 * replaced).
 */
export async function copyThemeAssets(root: string): Promise<void> {
  try {
    const entries = await Promise.all(
      THEME_TEMPLATE_FILES.map(
        async ({ source }) => [source, await getSpaceUiThemeTemplate(source)] as const,
      ),
    )
    await writeThemeFiles(root, Object.fromEntries(entries))
  } catch (error) {
    await cleanupThemeOutput(root)
    throw error
  }
}
