# .github/workflows/publish.yml

name: Prepare public

on:
  push:
    branches:
      - master 

jobs:
  prepare-public:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v2.x

      - name: Run Deno task build 
        run: deno task build
  
      - name: Upload build artifacts # To share between repos
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: |
            .dist/app.mjs
            deno.jsonc
            README.md
          retention-days: 1  

      - name: Checkout target repository (Public repo)
        uses: actions/checkout@v3
        with:
          repository: zanix-io/bundles-cli 
          token: ${{ secrets.GITHUB_TOKEN }} 
  
      - name: Download build artifacts and copy to target repository
        uses: actions/download-artifact@v3
        with:
          name: build-artifacts

      - name: List files in .
        run: ls -la ./

      - name: Copy build to target repository
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
      
          git add .
          git commit -m "Automatic build result"
          git push origin master  

      - name: Trigger trigger-publish-cli on Public repo
        run: |
          curl -X POST \
          https://api.github.com/repos/zanix-io/cli-bundle/dispatches \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -d '{"event_type": "trigger-publish-cli"}'